allowBuilds:
  '@scarf/scarf': false
  '@tree-sitter-grammars/tree-sitter-yaml': false
  bcrypt: true
  core-js: false
  core-js-pure: false
  esbuild: true
  nodemon: false
  tree-sitter: false
  tree-sitter-json: false
